---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

In the following classes we will be learning how to use `R` and `R studio` for data analysis. This will be a short introduction with the aim of getting you all familiar with the basics of how to use `R` for data management, exploring data, performing statistics, and plotting. There is a lot to learn in this short time but if you ever have any queries feel free to send me an [email](martin.garlovsky@tu-dresden.de) or find me in the Biology Building - room 258. 

A big shout out to [Professor Rob Knell](https://www.qmul.ac.uk/sbbs/staff/robknell.html) at Queen Mary, University of London, and [Dr. Dylan Childs](https://www.sheffield.ac.uk/biosciences/people/academic-staff/dylan-childs) and [Professor Andrew Beckerman](https://www.sheffield.ac.uk/biosciences/people/academic-staff/andrew-beckerman) at The University of Sheffield, who taught me how to use `R` and provided much of the inspiration for this course. They have excellent books available online which provide a more detailed introduction to using `R` and `R studio` as well as covering more advanced topics and statistical analysis. 

### [1. First session](First_session.html)
